import { Env } from './types';
export declare let hostedZones: {
    apigateway: {
        'us-east-2': string;
        'us-east-1': string;
        'us-west-1': string;
        'us-west-2': string;
        'ap-south-1': string;
        'ap-northeast-2': string;
        'ap-northeast-3': string;
        'ap-southeast-1': string;
        'ap-southeast-2': string;
        'ap-northeast-1': string;
        'ca-central-1': string;
        'eu-central-1': string;
        'eu-west-1': string;
        'eu-west-2': string;
        'eu-west-3': string;
        'sa-east-1': string;
    };
    cloudfront: string;
    elasticbeanstalk: {
        'us-east-2': string;
        'us-east-1': string;
        'us-west-1': string;
        'us-west-2': string;
        'ca-central-1': string;
        'ap-south-1': string;
        'ap-northeast-2': string;
        'ap-northeast-3': string;
        'ap-southeast-1': string;
        'ap-southeast-2': string;
        'ap-northeast-1': string;
        'eu-central-1': string;
        'eu-west-1': string;
        'eu-west-2': string;
        'eu-west-3': string;
        'sa-east-1': string;
    };
    elasticloadbalancing: {
        'us-east-2': string;
        'us-east-1': string;
        'us-west-1': string;
        'us-west-2': string;
        'ca-central-1': string;
        'ap-south-1': string;
        'ap-northeast-2': string;
        'ap-southeast-1': string;
        'ap-southeast-2': string;
        'ap-northeast-1': string;
        'eu-central-1': string;
        'eu-west-1': string;
        'eu-west-2': string;
        'eu-west-3': string;
        'sa-east-1': string;
        classic: {
            'us-east-2': string;
            'us-east-1': string;
            'us-west-1': string;
            'us-west-2': string;
            'ca-central-1': string;
            'ap-south-1': string;
            'ap-northeast-2': string;
            'ap-northeast-3': string;
            'ap-southeast-1': string;
            'ap-southeast-2': string;
            'ap-northeast-1': string;
            'eu-central-1': string;
            'eu-west-1': string;
            'eu-west-2': string;
            'eu-west-3': string;
            'sa-east-1': string;
        };
    };
    's3-website': {
        'us-east-2': string;
        'us-east-1': string;
        'us-west-1': string;
        'us-west-2': string;
        'ca-central-1': string;
        'ap-south-1': string;
        'ap-northeast-2': string;
        'ap-northeast-3': string;
        'ap-southeast-1': string;
        'ap-southeast-2': string;
        'ap-northeast-1': string;
        'eu-central-1': string;
        'eu-west-1': string;
        'eu-west-2': string;
        'eu-west-3': string;
        'sa-east-1': string;
    };
};
export declare let getHostedZoneId: ({ service, env, region }: {
    service: "acm" | "apigateway" | "application-autoscaling" | "autoscaling" | "cloudformation" | "cloudfront" | "cloudhsm" | "cloudsearch" | "cloudsearchdomain" | "cloudtrail" | "cloudwatch" | "codecommit" | "codepipeline" | "cognito-identity" | "cognito-idp" | "cognito-sync" | "configservice" | "configure" | "datapipeline" | "deploy" | "devicefarm" | "directconnect" | "discovery" | "dms" | "ds" | "dynamodb" | "dynamodbstreams" | "ec2" | "ecr" | "ecs" | "efs" | "elasticache" | "elasticbeanstalk" | "elastictranscoder" | "elb" | "emr" | "es" | "events" | "firehose" | "gamelift" | "glacier" | "help" | "iam" | "importexport" | "inspector" | "iot" | "iot-data" | "kinesis" | "kms" | "lambda" | "logs" | "machinelearning" | "marketplacecommerceanalytics" | "meteringmarketplace" | "opsworks" | "rds" | "redshift" | "route53" | "route53domains" | "s3" | "s3api" | "sdb" | "servicecatalog" | "ses" | "sns" | "sqs" | "ssm" | "storagegateway" | "sts" | "support" | "swf" | "waf" | "workspaces";
    env: Env;
    region?: string;
}) => string;
